### ISSUE TITLE
UV Sensor For Next TeHyBug?

### ISSUE THREAD

**Issue by KerstinMaur** [gumslone/tehybug#1]
I love the [TeHyBug](https://www.tindie.com/products/gumslone/low-power-temphumi-and-pressure-wifi-tracker-s5-2/) and am wondering if it would be possible to include an UV sensor in the next TeHyBug generation?

**Comment by gumslone** [comment]
Hello, the VEML6070 sensor has same pinout as the bme280 sensor. I think it should be possible, even it would be possible to use two sensors like bme280 and VEML6070 at the same time on the TeHyBug PCB. Will test it and write a code for it.

**Comment by KerstinMaur** [comment]
Is the [VEML6075](https://www.tindie.com/products/blkbox/veml6075-uv-ab-light-sensor-module-for-arduino/) compatible too?

**Comment by gumslone** [comment]
Hi, yes it should be compatible too, since its an i2c sensor, not sure about the code for it. The one you gave uses same pinout as i2c oled display, so it can be used instead of the i2c oled display on the TeHyBug PCB.

**Comment by KerstinMaur** [comment]
Can you add a TeHyBug with UV sensor to Tindie?

**Comment by gumslone** [comment]
Right now i'm testing it, do you mean a TeHyBug with only UV sensor or a TeHyBug which has two sensors like BME280 and VEML6070? The UV sensor measures the UV light intensity.

**Comment by KerstinMaur** [comment]
I am thinking of a pre-configured TeHyBug with two sensors on Tindie. 
But take your time, no stress, I do not want to hurry you. Sometime later this year is totally fine.

**Comment by gumslone** [comment]
ok, i have successfully tested it today and added it as an additional option to the TeHyBug with a BME280 sensor.

**Comment by Jean-Cote** [comment]
Just to be sure: Can I buy [Mini WIFI Temp/Humi and Pressure logger s5](https://www.tindie.com/products/gumslone/mini-wifi-temphumi-and-pressure-logger-s5/) for UV support?

**Comment by gumslone** [comment]
> Just to be sure: Can I buy [Mini WIFI Temp/Humi and Pressure logger s5](https://www.tindie.com/products/gumslone/mini-wifi-temphumi-and-pressure-logger-s5/) for UV support?

Hi, unfortunately, it's not been tested, it may work in a sandwich setup, UV sensor on top of the bme280 but I'm not sure if it will affect the data measurements of bme280. In a sandwich setup, it will work perfectly with the bme680 sensor, but I didn't release yet the TeHyBug s6 mini.

**Comment by KerstinMaur** [comment]
Was there some announcement for the s6? What are the plans for it?
I might buy that one too. 🤔
