### ISSUE TITLE
Multiple HTTP requests to update

### ISSUE THREAD

**Issue by larskotthoff** [gumslone/tehybug#2]
I want to use the tehybug with blynk, which provides a REST API (https://blynkapi.docs.apiary.io/#reference/0/write-pin-value-via-get/write-pin-value-via-get?console=1). Unfortunately it only allows to update a single virtual pin and a single value with each request.

Would it be possible to support multiple HTTP requests after each interval, e.g. specified as newline-separated URLs in the configuration interface?

**Comment by gumslone** [comment]
Hello Lars,

this is more an issue of a blynk api, 
logically i don't understand why they didn't create a feature to update multiple pins with a single http request.
Hope they will provide this option in their future api update.
Anyway there is a workaround to submit multiple values to blynk with a single TeHyBug request.
I have created a PHP script which will send the TeHyBug values to multiple pins at blynk, you'll have to point your TeHyBug to the script. The script should work with most webhosts or even free webhosts which support php. The script is uploaded to this github repo.

Optionally i have uploaded the script to the tehybug.com server, so you can point your tehybug (in the custom get configuration mode) to:
http://tehybug.com/blynk/auth_token/tokenvaluegoeshere/?pins=V0,V1,V2&values=%temp%,%humi%,%qfe% 

this will set the virtual pin V0 to the temperature value and so on.

also don't forget to replace the "tokenvaluegoeshere" with your auth token provided by blynk.

**Comment by larskotthoff** [comment]
Thanks, that's great, I'll try this as soon as I get a chance and will report back.

**Comment by larskotthoff** [comment]
I'm getting "Invalid token." when GETing the tehybug.com URL. I've checked that the token is correct.

**Comment by gumslone** [comment]
Hello Lars, 
I have tested it with my test auth token, which is:

----

The test url looks like:

http://tehybug.com/blynk/auth_token/----/?pins=V0,V1,V2&values=11,22,33

It sets V0 to 11
V1 to 22
V2 to 33

Works for me

**Comment by larskotthoff** [comment]
Hmm, is there any special setup for the blynk project required? I've set up a test project and I'm getting the same error:

    curl 'http://tehybug.com/blynk/auth_token/-----/?pins=V0&values=1'

    string(14) "Invalid token."
    <br>Pin <b>V0</b> is set to <b>1</b><br>

**Comment by larskotthoff** [comment]
I'm running your script on a local PHP server now and that works. Thanks!
