### ISSUE TITLE
Unable to reset bug

### ISSUE THREAD

**Issue by robotamer** [gumslone/tehybug#4]
Hi
I am unable to reset/enter configuration mode on my bug.   
My bug is  
 ```
TeHyBug_15575022
TeHyBug key: f4b5d168-7b1b-427e-a5b5-d9800c017f9e 
```

I am clicking reset (black) and then red button. I have done this many times before but somehow it wont work anymore. I have tried red and then black button as well.
Is there any other way to reset?

**Comment by gumslone** [comment]
Hi,

does the blue LED blink when you hit the reset button?

does it receive enough power?

Sometimes when the battery is drained it cant be reseted, 5V input power should be fine.

**Comment by robotamer** [comment]
It is connected to USB 5V 2.4A.
Yes the blue light blinks, but it fails to light solid. 
I love this bug, I am writing a program for it in Go and html using MQTT that will eventually be open source, naturally. I guess I did the reset while testing once too many times. :) 
If we can't resolve this I will order a new one. However I live on a sailboat and I am currently in Turkey so it is kind of hard to receive something here. So it would be nice if we can resolve this.

**Comment by gumslone** [comment]
Hi,
If you use the default firmware and you hit reset and mode button several times very often and fast one after another, the config file could be damaged, you'll have to upload a new file via the programmer, but I'm not sure about it.
Can you do debugging, connect the ESP-01 Module to an Esp-01 programmer and read the serial output?

**Comment by robotamer** [comment]
I haven't done the "several times very often and fast one after another" thing.
I don't have the hardware. Can I read directly from the USB port on the bug?

**Comment by gumslone** [comment]
Hi, 
it wouldn't work via USB, the Micro-USB port on the board is for power delivery only, you'll need an ESP-01 programmer for debugging.
