### ISSUE TITLE
AirQulity parameter reports the same value

### ISSUE THREAD

**Issue by igoraj** [gumslone/tehybug#6]
I recently got a Mini WIFI Temp/Humi and Pressure, AirQ logger s6 ordered from Tindie which seems to be reporting the same constant value for AirQuality (it's always 0.177) 

e.g.:
`/?t=21.34&h=62.96&p=978.59&a=0.177`

Is there something else I need to do in order to get it working?

**Comment by gumslone** [comment]
Hi, what does it show when you go into configuration mode and select the current environment data?

**Comment by igoraj** [comment]
<img width="327" alt="curr-env" src="https://user-images.githubusercontent.com/1874763/94850304-0c357e00-0427-11eb-8660-5eeb7a606a8a.png">

**Comment by gumslone** [comment]
Hi, looks strange, I will do some tests on my side and will get back to you, if its not a software issue which can be fixed ill ship you a replacement. Thanks

**Comment by igoraj** [comment]
hey @gumslone, have you managed to figure out anything?

**Comment by gumslone** [comment]
Hi,
it's not a software issue, 0.177 is delivered when the sensor is not delivering any data, not connected or defective, might be that the tiny square sensor is not properly connected to the sensor board (loose solder connection). Anyway, I have prepared a replacement and will ship it tomorrow.

**Comment by igoraj** [comment]
Hey this one is more lively, so thanks 🙏.

Do you happen to know how Ohm reading map to Air Quality?
